#!/usr/bin/env bash
set -euo pipefail

BACKGROUND_MODE="black"

for arg in "$@"; do
    case "$arg" in
        --blackbackground)
            BACKGROUND_MODE="black"
            ;;
        --greybackground)
            BACKGROUND_MODE="grey"
            ;;
    esac
done

# Configs
REPO_URL="https://github.com/sorinbotirla/Raspberry-Pi-FLIR-Lepton-Thermal-Imaging-Camera.git"
REPO_DIRNAME="Raspberry-Pi-FLIR-Lepton-Thermal-Imaging-Camera"
APP_SUBDIR="LeptonModule/software/raspberrypi_video"
SERVICE_NAME="lepton-view.service"

# Composite / overscan (override by exporting vars before running)
# Example:
#   sudo OVERSCAN_RIGHT=-14 OVERSCAN_TOP=-14 OVERSCAN_BOTTOM=-14 ./setupleptonrpi.sh
SDTV_MODE="${SDTV_MODE:-2}"         # 2=PAL, 0=NTSC
SDTV_ASPECT="${SDTV_ASPECT:-3}"     # 3=16:9, 1=4:3
OVERSCAN_LEFT="${OVERSCAN_LEFT:-0}"
OVERSCAN_RIGHT="${OVERSCAN_RIGHT:--14}"
OVERSCAN_TOP="${OVERSCAN_TOP:--14}"
OVERSCAN_BOTTOM="${OVERSCAN_BOTTOM:--14}"

# App defaults
COLORMAP="${COLORMAP:-3}"          # 1=rainbow, 2=grayscale, 3=ironblack
SPI_SPEED_MHZ="${SPI_SPEED_MHZ:-20}" # 10..30

# Helpers
log() { printf '%s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
have_cmd() { command -v "$1" >/dev/null 2>&1; }

backup_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  cp -a "$f" "${f}.bak.$(date +%Y%m%d-%H%M%S)"
}

set_or_append() {
  local key="$1"
  local val="$2"
  local file="$3"
  if grep -qE "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${val}|" "$file"
  else
    printf '%s=%s\n' "$key" "$val" >> "$file"
  fi
}

# Permission and OS Requirements
[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Run as root: sudo $0"
have_cmd apt-get || die "apt-get not found."

# Find target user/home (not installing under /root folder)
TARGET_USER="${SUDO_USER:-}"
if [[ -z "$TARGET_USER" || "$TARGET_USER" == "root" ]]; then
  TARGET_USER="$(awk -F: '$3>=1000 && $1!="nobody"{print $1; exit}' /etc/passwd || true)"
fi
[[ -n "$TARGET_USER" ]] || die "Could not determine a non-root target user."
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
[[ -n "$TARGET_HOME" && -d "$TARGET_HOME" ]] || die "Target home not found for $TARGET_USER: $TARGET_HOME"

INSTALL_DIR="/home/${TARGET_USER}/${REPO_DIRNAME}"
APP_DIR="$INSTALL_DIR/$APP_SUBDIR"
BIN_PATH="$APP_DIR/raspberrypi_video"

# If the user already cloned the repo and runs this script from inside it,
# prefer that working tree instead of cloning again.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -d "$SCRIPT_DIR/LeptonModule/software/raspberrypi_video" ]; then
  INSTALL_DIR="$SCRIPT_DIR"
  APP_DIR="$INSTALL_DIR/$APP_SUBDIR"
  BIN_PATH="$APP_DIR/raspberrypi_video"
fi


# Clock skew error fix, well it might happen otherwise
log "[1/10] Time sync..."
systemctl enable --now systemd-timesyncd.service >/dev/null 2>&1 || true

# Package Requirements
log "[2/10] Packages..."
apt-get update
apt-get install -y --no-install-recommends \
  git ca-certificates \
  raspi-config \
  build-essential make g++ pkg-config \
  qt5-qmake qtbase5-dev qtbase5-dev-tools \
  libqt5gui5 libqt5widgets5 libqt5core5a \
  libgles2-mesa-dev \
  ffmpeg \
  fbset

# Interface Requirements (SPI/I2C/rootfs)
log "[3/10] Enable SPI + I2C, expand rootfs..."
raspi-config nonint do_spi 0 || true
raspi-config nonint do_i2c 0 || true
raspi-config nonint do_expand_rootfs || true

# Boot configuration
# Apply to /boot/firmware if present, and also /boot if it contains config/cmdline
apply_boot_edits() {
  local dir="$1"
  local cfg="$dir/config.txt"
  local cmd="$dir/cmdline.txt"
  [[ -f "$cfg" && -f "$cmd" ]] || return 0

  log "  Boot edits in: $dir"
  backup_file "$cfg"
  backup_file "$cmd"

  # Ensure fb0 + linuxfb workable: remove full KMS, enforce FKMS
  sed -i '/^dtoverlay=vc4-kms-v3d$/d' "$cfg"
  grep -qE '^dtoverlay=vc4-fkms-v3d$' "$cfg" || printf '%s\n' 'dtoverlay=vc4-fkms-v3d' >> "$cfg"

  # Composite video (CVBS) + force ignore HDMI hotplug
  set_or_append "enable_tvout" "1" "$cfg"
  set_or_append "hdmi_ignore_hotplug" "1" "$cfg"
  set_or_append "sdtv_mode" "$SDTV_MODE" "$cfg"
  set_or_append "sdtv_aspect" "$SDTV_ASPECT" "$cfg"

  # Overscan (negative values allowed)
  set_or_append "disable_overscan" "0" "$cfg"
  set_or_append "overscan_left" "$OVERSCAN_LEFT" "$cfg"
  set_or_append "overscan_right" "$OVERSCAN_RIGHT" "$cfg"
  set_or_append "overscan_top" "$OVERSCAN_TOP" "$cfg"
  set_or_append "overscan_bottom" "$OVERSCAN_BOTTOM" "$cfg"

  # Match fb0 depth (CVBS commonly 16bpp)
  set_or_append "framebuffer_depth" "16" "$cfg"
  set_or_append "framebuffer_ignore_alpha" "1" "$cfg"

  # Keep 2 framebuffers to reduce fb flicker/blanking on some setups
  set_or_append "max_framebuffers" "2" "$cfg"
  set_or_append "disable_fw_kms_setup" "1" "$cfg"

  # cmdline MUST be a single line (no banners, no weird chars)
  local line
  line="$(tr -d '\r\n' < "$cmd" | tr -s ' ')"

  # If this is a Bookworm stub file, do not touch it
  echo "$line" | grep -q "DO NOT EDIT THIS FILE" && return 0

  # Remove any existing console targets and verbosity flags
  line="$(echo "$line" | sed -E 's/\bconsole=[^ ]+\b//g; s/\bloglevel=[^ ]+\b//g; s/\bquiet\b//g; s/\bconsoleblank=[^ ]+\b//g; s/\bsystemd\.show_status=[^ ]+\b//g; s/\brd\.udev\.log_level=[^ ]+\b//g; s/\blogo\.nologo\b//g; s/\bvt\.global_cursor_default=[^ ]+\b//g' | tr -s ' ')"

  # Add the flags we want
  line="$line console=tty3 quiet loglevel=0 consoleblank=0 systemd.show_status=0 rd.udev.log_level=0 logo.nologo vt.global_cursor_default=0"

  # Write back as exactly ONE newline-terminated line
  printf '%s\n' "$(echo "$line" | tr -s ' ' | sed -E 's/^ +| +$//g')" > "$cmd"
}

log "[4/10] Apply boot edits (embedded settings, no zip)..."
apply_boot_edits "/boot/firmware"

# Services and boot journals cleanup, you won't get direct login anymore, but ssh will still work
log "[5/10] Prevent console from reclaiming tty1..."
systemctl disable --now getty@tty1.service >/dev/null 2>&1 || true
systemctl mask getty@tty1.service >/dev/null 2>&1 || true
systemctl disable --now serial-getty@serial0.service >/dev/null 2>&1 || true
systemctl mask serial-getty@serial0.service >/dev/null 2>&1 || true

# Qt runtime dir
log "[6/10] Qt runtime dir..."
mkdir -p /tmp/runtime-root
chown root:root /tmp/runtime-root
chmod 0700 /tmp/runtime-root

# Clone / update repo (only if we are not already running inside a cloned repo)
log "[7/10] Repo: $REPO_URL"
if [ "$INSTALL_DIR" = "$SCRIPT_DIR" ] && [ -d "$INSTALL_DIR/.git" ]; then
  log "Repo already present at $INSTALL_DIR (running from inside the clone). Skipping git clone."
else
  if [ -d "$INSTALL_DIR" ]; then
    log "Removing existing clone at $INSTALL_DIR ..."
    rm -rf "$INSTALL_DIR"
  fi
  log "Cloning into $INSTALL_DIR ..."
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
  chown -R "$TARGET_USER:$TARGET_USER" "$INSTALL_DIR"
fi

log "[8/10] Build..."

sudo -u "$TARGET_USER" sh -c "
    cd '$APP_DIR' &&
    make distclean >/dev/null 2>&1 || true &&
    rm -f Makefile .qmake.stash &&
    rm -rf gen_objs gen_mocs &&
    qmake &&
    make -j1
"

[[ -x "$BIN_PATH" ]] || die "Build failed: $BIN_PATH not found."

CFG_PATH="$APP_DIR/config.json"
if [[ ! -f "$CFG_PATH" ]]; then
  cat > "$CFG_PATH" <<'JSON'
{
  "background": "black",
  "thermal": {
    "enabled": true,
    "flip_h": false,
    "flip_v": false,
    "offset_x": 0,
    "offset_y": 0,
    "opacity": 1.0,
    "rotate_deg": 0,
    "scale": 1.0,
    "smooth": 0
  },
  "usb_cam": {
    "enabled": true,
    "device": "/dev/video0",
    "width": 640,
    "height": 480,
    "fps": 15,
    "flip_h": false,
    "flip_v": false,
    "offset_x": 0,
    "offset_y": 0,
    "opacity": 1.0,
    "rotate_deg": 0,
    "scale": 1.0,
    "emboss": false
  }
}
JSON
  chown "$TARGET_USER:$TARGET_USER" "$CFG_PATH"
fi

# Create the lepton view service
log "[9/10] Install systemd service..."
# Remove any older drop-in overrides from previous installs (they override ExecStart)
rm -rf "/etc/systemd/system/${SERVICE_NAME}.d" >/dev/null 2>&1 || true

cat > "/etc/systemd/system/$SERVICE_NAME" <<EOF
[Unit]
Description=Lepton thermal view (Qt linuxfb)
After=local-fs.target systemd-udev-trigger.service
Wants=systemd-udev-trigger.service

[Service]
Type=simple
WorkingDirectory=$APP_DIR

Environment=QT_QPA_PLATFORM=linuxfb
Environment=QT_QPA_FB=/dev/fb0
Environment=XDG_RUNTIME_DIR=/tmp/runtime-root

ExecStartPre=/bin/rm -f /tmp/lepton_cmd
ExecStartPre=/usr/bin/mkfifo /tmp/lepton_cmd
ExecStartPre=/bin/chmod 666 /tmp/lepton_cmd

StandardInput=tty
StandardOutput=tty
StandardError=tty
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes

ExecStart=$BIN_PATH -cm $COLORMAP -ss $SPI_SPEED_MHZ
Restart=always
RestartSec=1
StartLimitIntervalSec=0

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"

log "Rebooting to apply boot settings..."
sleep 2

# Reboot and say hello to your new FLIR Cam
reboot
